#include "quiklight_hid.hpp"
#include <setupapi.h>
#include <algorithm>
#include <sstream>
#include <stdexcept>
#include <iomanip>
#include <cwctype>
#pragma comment(lib,"setupapi.lib")
#pragma comment(lib,"hid.lib")
namespace quiklight {
static uint8_t checksum8(const std::vector<uint8_t>&d){uint32_t s=0;for(auto b:d)s+=b;return(uint8_t)s;}
static std::wstring getstr(HANDLE h, DWORD which){WCHAR b[256]{};BOOLEAN ok=FALSE;if(which==0)ok=HidD_GetManufacturerString(h,b,sizeof(b));else if(which==1)ok=HidD_GetProductString(h,b,sizeof(b));else ok=HidD_GetSerialNumberString(h,b,sizeof(b));return ok?std::wstring(b):L"";}
std::vector<HidDeviceInfo> QuiklightHid::listDevices(){std::vector<HidDeviceInfo>out;GUID g;HidD_GetHidGuid(&g);HDEVINFO info=SetupDiGetClassDevsW(&g,nullptr,nullptr,DIGCF_PRESENT|DIGCF_DEVICEINTERFACE);if(info==INVALID_HANDLE_VALUE)return out;SP_DEVICE_INTERFACE_DATA id{};id.cbSize=sizeof(id);for(DWORD i=0;SetupDiEnumDeviceInterfaces(info,nullptr,&g,i,&id);i++){DWORD need=0;SetupDiGetDeviceInterfaceDetailW(info,&id,nullptr,0,&need,nullptr);if(!need)continue;auto buf=std::vector<BYTE>(need);auto detail=reinterpret_cast<PSP_DEVICE_INTERFACE_DETAIL_DATA_W>(buf.data());detail->cbSize=sizeof(*detail);if(!SetupDiGetDeviceInterfaceDetailW(info,&id,detail,need,nullptr,nullptr))continue;HANDLE h=CreateFileW(detail->DevicePath,GENERIC_READ|GENERIC_WRITE,FILE_SHARE_READ|FILE_SHARE_WRITE,nullptr,OPEN_EXISTING,FILE_FLAG_OVERLAPPED,nullptr);if(h==INVALID_HANDLE_VALUE)h=CreateFileW(detail->DevicePath,GENERIC_WRITE,FILE_SHARE_READ|FILE_SHARE_WRITE,nullptr,OPEN_EXISTING,0,nullptr);if(h==INVALID_HANDLE_VALUE)continue;HIDD_ATTRIBUTES a{};a.Size=sizeof(a);if(HidD_GetAttributes(h,&a)){HIDP_CAPS caps{};PHIDP_PREPARSED_DATA pp=nullptr;DWORD outlen=65;if(HidD_GetPreparsedData(h,&pp)){if(HidP_GetCaps(pp,&caps)==HIDP_STATUS_SUCCESS&&caps.OutputReportByteLength)outlen=caps.OutputReportByteLength;HidD_FreePreparsedData(pp);}out.push_back({detail->DevicePath,a.VendorID,a.ProductID,getstr(h,0),getstr(h,1),getstr(h,2),outlen});}CloseHandle(h);}SetupDiDestroyDeviceInfoList(info);return out;}
QuiklightHid::QuiklightHid(uint16_t vid,uint16_t pid,uint8_t b,const std::wstring&p):vid_(vid),pid_(pid),brightness_(b),forced_path_(p){open();initialize();}
QuiklightHid::~QuiklightHid(){if(dev_!=INVALID_HANDLE_VALUE)CloseHandle(dev_);}
void QuiklightHid::open(){std::wstring chosen=forced_path_;if(chosen.empty()){for(const auto&d:listDevices()){if(d.vendor_id==vid_&&d.product_id==pid_){chosen=d.path;report_len_=d.output_report_len;if(d.manufacturer.find(L"ROBOBLOQ")!=std::wstring::npos||d.product.find(L"USBHID")!=std::wstring::npos)break;}}}if(chosen.empty())throw std::runtime_error("Quiklight HID device not found (VID=1A86 PID=FE07)");dev_=CreateFileW(chosen.c_str(),GENERIC_WRITE|GENERIC_READ,FILE_SHARE_READ|FILE_SHARE_WRITE,nullptr,OPEN_EXISTING,0,nullptr);if(dev_==INVALID_HANDLE_VALUE){std::string msg="Failed to open Quiklight HID device";throw std::runtime_error(msg);}if(HIDD_ATTRIBUTES a{sizeof(a)};HidD_GetAttributes(dev_,&a)){PHIDP_PREPARSED_DATA pp=nullptr;HIDP_CAPS caps{};if(HidD_GetPreparsedData(dev_,&pp)){if(HidP_GetCaps(pp,&caps)==HIDP_STATUS_SUCCESS&&caps.OutputReportByteLength)report_len_=caps.OutputReportByteLength;HidD_FreePreparsedData(pp);}}if(report_len_<65)report_len_=65;}
bool QuiklightHid::sendFrame(const LedFrame&f){return sendPacket(sync(f));}
bool QuiklightHid::setBrightness(uint8_t value){brightness_=value; return sendPacket(makeBrightnessPacket(value));}
void QuiklightHid::initialize(){if(!sendPacket(setOpen()))throw std::runtime_error("Failed to initialize Quiklight (setOpen)");if(!sendPacket(makeBrightnessPacket(brightness_)))throw std::runtime_error("Failed to initialize Quiklight (brightness)");if(!sendPacket(setSection()))throw std::runtime_error("Failed to initialize Quiklight (section)");LedFrame black{};if(!sendFrame(black))throw std::runtime_error("Failed to initialize Quiklight (black frame)");}
bool QuiklightHid::sendPacket(const std::vector<uint8_t>&p){size_t off=0;while(off<p.size()){std::vector<uint8_t> report(report_len_,0);size_t chunk=std::min<size_t>(report_len_-1,p.size()-off);report[0]=0;memcpy(report.data()+1,p.data()+off,chunk);DWORD wr=0;if(!WriteFile(dev_,report.data(),(DWORD)report.size(),&wr,nullptr))return false;off+=chunk;}return true;}
std::vector<uint8_t> QuiklightHid::simple(uint8_t id,uint8_t action,const uint8_t*payload,size_t len)const{std::vector<uint8_t>o;o.reserve(2+1+1+1+len+1);o.push_back('R');o.push_back('B');o.push_back((uint8_t)(2+1+1+1+len+1));o.push_back(id);o.push_back(action);o.insert(o.end(),payload,payload+len);o.push_back(checksum8(o));return o;}
std::vector<uint8_t> QuiklightHid::setOpen()const{uint8_t p[]={0};return simple(next_msg_id_++,147,p,1);}
std::vector<uint8_t> QuiklightHid::makeBrightnessPacket(uint8_t v)const{uint8_t p[]={v};return simple(next_msg_id_++,135,p,1);}
std::vector<uint8_t> QuiklightHid::setSection()const{uint8_t p[]={1,85,85,85,63,64,0,0,0,254};return simple(next_msg_id_++,134,p,10);}
std::vector<uint8_t> QuiklightHid::sync(const LedFrame&f)const{const size_t plen=kLedCount*5,total=2+2+1+1+plen+1;std::vector<uint8_t>o;o.reserve(total);o.push_back('S');o.push_back('C');o.push_back((uint8_t)(total>>8));o.push_back((uint8_t)total);o.push_back(next_msg_id_++);o.push_back(128);for(size_t i=0;i<f.size();i++){uint8_t n=(uint8_t)(i+1);o.push_back(n);o.push_back(f[i].r);o.push_back(f[i].g);o.push_back(f[i].b);o.push_back(n);}o.push_back(checksum8(o));return o;}
}
